create or replace TABLE ODS_DEV.STAGING.CAR (
	VEHICLE_ID NUMBER(38,0) NOT NULL,
	POLICY_NUM NUMBER(38,0),
	CUST_ID NUMBER(38,0),
	MAKE VARCHAR(16777216),
	MODEL_NUM VARCHAR(16777216),
	DOORS NUMBER(38,0),
	YEAR NUMBER(38,0),
	COLOR VARCHAR(16777216),
	primary key (VEHICLE_ID),
	foreign key (POLICY_NUM) references ODS_DEV.STAGING.POLICY(POLICY_NUM),
	foreign key (CUST_ID) references ODS_DEV.STAGING.CUSTOMER(CUST_ID)
);
