create or replace TABLE ODS_DEV.STAGING.EXPENSES (
	EXPENSE_ID VARCHAR(16777216) NOT NULL,
	CUST_ID NUMBER(38,0),
	POLICY_NUM NUMBER(38,0),
	AGENT_ID NUMBER(38,0),
	EXPENSE_TYP VARCHAR(16777216),
	AMOUNT NUMBER(38,0),
	DESCRIPTION VARCHAR(16777216),
	DATE DATE,
	primary key (EXPENSE_ID),
	foreign key (CUST_ID) references ODS_DEV.STAGING.CUSTOMER(CUST_ID),
	foreign key (POLICY_NUM) references ODS_DEV.STAGING.POLICY(POLICY_NUM)
);
