create or replace TABLE ODS_DEV.STAGING.HEALTH_CARE (
	REPORT_ID NUMBER(38,0) NOT NULL,
	POLICY_NUM NUMBER(38,0),
	CUST_ID NUMBER(38,0),
	DATE DATE,
	primary key (REPORT_ID),
	foreign key (POLICY_NUM) references ODS_DEV.STAGING.POLICY(POLICY_NUM),
	foreign key (CUST_ID) references ODS_DEV.STAGING.CUSTOMER(CUST_ID)
);
