create or replace TABLE ODS_DEV.STAGING.HOUSE (
	HOUSE_ID NUMBER(38,0) NOT NULL,
	CUST_ID NUMBER(38,0),
	POLICY_NUM NUMBER(38,0),
	HOUSE_COST NUMBER(10,2),
	primary key (HOUSE_ID),
	foreign key (POLICY_NUM) references ODS_DEV.STAGING.POLICY(POLICY_NUM),
	foreign key (CUST_ID) references ODS_DEV.STAGING.CUSTOMER(CUST_ID)
);
