create or replace TABLE ODS_DEV.STAGING.PAYMENT (
	PAYMENT_ID NUMBER(38,0) NOT NULL,
	CUST_ID NUMBER(38,0),
	PAYMENT_DATE DATE,
	POLICY_NUM NUMBER(38,0),
	PAYMENT_AMOUNT NUMBER(10,2),
	primary key (PAYMENT_ID),
	foreign key (CUST_ID) references ODS_DEV.STAGING.CUSTOMER(CUST_ID),
	foreign key (POLICY_NUM) references ODS_DEV.STAGING.POLICY(POLICY_NUM)
);
