create or replace TABLE ODS_DEV.STAGING.POLICY (
	POLICY_NUM NUMBER(38,0) NOT NULL,
	PAYMENT_ID NUMBER(38,0),
	CUST_ID NUMBER(38,0),
	AGENT_ID NUMBER(38,0),
	TYPE VARCHAR(16777216),
	COVERAGE VARCHAR(16777216),
	TERM_PRICE NUMBER(10,2),
	ISSUED_DATE DATE,
	DEDUCTIBLE NUMBER(10,2),
	primary key (POLICY_NUM),
	foreign key (CUST_ID) references ODS_DEV.STAGING.CUSTOMER(CUST_ID)
);
