create or replace TABLE ODS_DEV.STAGING.PROFIT_AND_LOSS (
	CUST_ID NUMBER(38,0),
	POLICY_NUM NUMBER(38,0),
	AGENT_ID NUMBER(38,0),
	TOTAL_REVENUE NUMBER(10,2),
	TOTAL_EXPENSES NUMBER(10,2),
	PROFIT_LOSS NUMBER(10,2),
	foreign key (CUST_ID) references ODS_DEV.STAGING.CUSTOMER(CUST_ID),
	foreign key (AGENT_ID) references ODS_DEV.STAGING.AGENT(AGENT_ID),
	foreign key (POLICY_NUM) references ODS_DEV.STAGING.POLICY(POLICY_NUM)
);
