create or replace TABLE ODS_DEV.STAGING.REVENUE (
	REVENUE_ID VARCHAR(16777216) NOT NULL,
	POLICY_NUM NUMBER(38,0),
	CUST_ID NUMBER(38,0),
	REVENUE_AMOUNT NUMBER(10,2),
	primary key (REVENUE_ID),
	foreign key (POLICY_NUM) references ODS_DEV.STAGING.POLICY(POLICY_NUM),
	foreign key (CUST_ID) references ODS_DEV.STAGING.CUSTOMER(CUST_ID)
);
