create or replace TABLE ODS_DEV.STAGING.SALES_TRANSACTIONS (
	TRANSACTION_ID VARCHAR(16777216) NOT NULL,
	CUST_ID NUMBER(38,0),
	PRODUCT_ID VARCHAR(16777216),
	SALE_DATE DATE,
	QUANTITY NUMBER(38,0),
	TOTAL_PRICE NUMBER(10,2),
	primary key (TRANSACTION_ID),
	foreign key (CUST_ID) references ODS_DEV.STAGING.CUSTOMER(CUST_ID)
);
