create or replace TRANSIENT TABLE DEV_ENV.DBT_DEV.DIM_CLAIMS (
	CLAIM_ID NUMBER(38,0),
	POLICY_NUM NUMBER(38,0),
	CLAIM_TYPE VARCHAR(16777216),
	CLAIM_STATUS VARCHAR(16777216),
	PAYMENT_AMOUNT NUMBER(38,0),
	SETTLEMENT_DATE DATE,
	CLAIM_DATE DATE
);
